M48
; DRILL file {KiCad (6.0.11)} date Mon Aug 21 22:45:38 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-21T22:45:38+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X55.0Y-55.0
X55.0Y-145.0
X145.0Y-55.0
X145.0Y-145.0
T0
M30
